### ISSUE TITLE
Assignment without file submission does not update in the list of submitted activities

### ISSUE THREAD

**Issue by horstschneider** [fernandooliveira/moodle-block_mentor#33] opened 2016-11-24 18:27 UTC
Dear all,
In the list of submitted activities we have several quizzes and assignments in our moodle course.
Some of the assignments are used to reflect practical exams/assessments in moodle. For these assignments the students do not need to submitt any files. The trainer provides the feedback on the assessment and grades according to the result of the assessments. We use a pass grade for these assignments.

Assignments with file submissions are updated in the mentor manager, assignments without file submission do not update, i.e. they remain blank in the list of submitted activities even if the trainer provided feedback and grades.

We changed the settings for such an assignment to allow for file submissions. Once uploaded it updated the list.

As we would like to use the assignments for such assessments without file submission it would be nice if you could adjust the behaviour of the mentor manager to update also assignments without file submissions.

Kind regards

Horst

**Comment by fernandooliveira** [comment] 2016-11-24 19:07
Hello Horst,

I am not able to reproduce the problem that you described. The Marking Manager is able to grade assignments with online text as well as file attachments. Can you provide more info?

**Comment by horstschneider** [comment] 2016-11-24 19:14
Hello Fernando,
It is the Mentor Manager, not the Marking Manager where we encounter issues.
If the student is not allowed to submit anything (neither online text nor file submissions) then the mentor managager does not update this activity after the teacher provided feedback and a grade.
Hope this clarifies.

**Comment by fernandooliveira** [comment] 2016-11-24 19:34
My apologies. I will look into this.

**Comment by fernandooliveira** [comment] 2017-01-03 21:22
Hello Horst,

This should be fixed. Please test.

**Closed by fernandooliveira** 2017-01-03 21:22 UTC

**Comment by horstschneider** [comment] 2017-01-10 16:02
Hello Fernando,
Tanks for fixing this.
And sorry for the delayed reply.
Kind regards
Horst

Von meinem iPad gesendet



Am 03.01.2017 um 22:22 schrieb NED <notifications@github.com<mailto:notifications@github.com>>:


Closed #33<https://github.com/fernandooliveira/moodle-block_mentor/issues/33>.

-
